// =============================================================================
// secded_test.sv — SECDED-specific directed tests
// These tests are run as part of the full environment (T4, T5, T7).
// This file documents the SECDED-specific test intent.
//
// T4: Single-bit error injection
//   - Write weight W to memory
//   - Flip one codeword bit during read
//   - Expect: single_error_corrected=1, corrected_weight==W, correct inference
//
// T5: Double-bit error injection
//   - Write weight W to memory
//   - Flip two codeword bits during read
//   - Expect: double_error_detected=1
//
// These scenarios are generated by bnn_generator.sv and verified by
// bnn_scoreboard.sv golden model.
// =============================================================================

`ifndef SECDED_TEST_SV
`define SECDED_TEST_SV
// No additional code needed; tests are generated in bnn_generator.sv
`endif
