// Auto-generated by OpenLane
module are_ubnn_kws_baseline_wrapper(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[255:0] activations_flat,
  input[8:0] threshold,
  input accum_en,
  input wr_en,
  input[3:0] wr_addr,
  input[15:0] wr_data,
  input[3:0] rd_addr,
  input[255:0] direct_weights_flat,
  input fault_inject_en,
  input[21:0] fault_mask,
  output keyword_detected,
  output[8:0] accumulated_sum,
  output[15:0] pe_active,
  output single_error_corrected,
  output double_error_detected,
  output accum_valid
);
endmodule
